const fs = require('fs');
const path = require('path');

function makeCell(row, col, props = {}) {
  return Object.assign({ row, col }, props);
}

function randInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function formatNumber(n) {
  return n.toLocaleString('en-US');
}

const initialCells = [];
const mergedCells = [];

// Title
initialCells.push(makeCell(1, 1, { text: 'Market Snapshot', bold: true, fontSize: 14, ta: 'left', bc: '#0b1013', color: '#ffd24a' }));
mergedCells.push({ r1: 1, c1: 1, r2: 1, c2: 8 });

// Column headers (row 3)
const headers = ['Date', 'Ticker', 'Price', 'Change', '%', 'Volume', 'Market', 'Note'];
headers.forEach((h, i) => {
  initialCells.push(makeCell(3, i + 1, { text: h, bold: true, ta: 'center', bc: '#1b1f24', color: '#ffd24a' }));
});

// A few curated sample tickers (rows 4..12)
const curated = [
  ['2026-02-28', 'ACME', 312.45, +2.34, '+0.75%', 1245600, 'Large Cap', 'Top pick'],
  ['2026-02-28', 'ORCL', 78.12, -0.56, '-0.71%', 605400, 'Large Cap', 'Earnings soon'],
  ['2026-02-28', 'NOVA', 22.90, +0.15, '+0.66%', 98000, 'Small Cap', 'Momentum'],
  ['2026-02-28', 'GLBX', 145.00, -1.20, '-0.82%', 240000, 'Mid Cap', 'Buyback announced'],
];
let r = 4;
curated.forEach(row => {
  initialCells.push(makeCell(r, 1, { text: row[0], ta: 'center', bc: '#060708', color: '#c9d1d9' }));
  initialCells.push(makeCell(r, 2, { text: row[1], ta: 'left', bc: '#060708', color: '#ffffff' }));
  initialCells.push(makeCell(r, 3, { text: String(row[2]), ta: 'right', bc: '#060708', color: '#9be6a6' }));
  const changeColor = String(row[3]).startsWith('-') ? '#ff6b6b' : '#23d160';
  const changeBg = changeColor === '#23d160' ? '#07110a' : '#2a0d0d';
  initialCells.push(makeCell(r, 4, { text: String(row[3]), ta: 'right', color: changeColor, bc: changeBg }));
  initialCells.push(makeCell(r, 5, { text: String(row[4]), ta: 'right', color: changeColor, bc: changeBg }));
  initialCells.push(makeCell(r, 6, { text: formatNumber(row[5]), ta: 'right', bc: '#060708', color: '#c9d1d9' }));
  initialCells.push(makeCell(r, 7, { text: row[6], ta: 'left', bc: '#060708', color: '#c9d1d9' }));
  initialCells.push(makeCell(r, 8, { text: row[7], ta: 'left', bc: '#060708', color: '#dbe7ff' }));
  r++;
});

// Fixed Income header sample (keeps earlier sections compact)
initialCells.push(makeCell(20, 1, { text: 'Fixed Income Trading', bold: true, fontSize: 13, ta: 'left', bc: '#0b1013', color: '#ffd24a' }));
mergedCells.push({ r1: 20, c1: 1, r2: 20, c2: 8 });
initialCells.push(makeCell(21, 1, { text: 'Ticker', bold: true, ta: 'left', bc: '#1b1f24', color: '#ffd24a' }));
initialCells.push(makeCell(21, 2, { text: 'Price', bold: true, ta: 'right', bc: '#1b1f24', color: '#ffd24a' }));
initialCells.push(makeCell(21, 3, { text: 'Yield', bold: true, ta: 'right', bc: '#1b1f24', color: '#ffd24a' }));

// Add a handful of fixed income rows
const fi = [
  ['US10Y', '103.125', '1.85%'],
  ['US2Y', '99.750', '4.05%'],
  ['CORP5Y', '101.500', '3.45%']
];
let fiR = 22;
fi.forEach(item => {
  initialCells.push(makeCell(fiR, 1, { text: item[0], ta: 'left', bc: '#060708', color: '#ffffff' }));
  initialCells.push(makeCell(fiR, 2, { text: item[1], ta: 'right', bc: '#060708', color: '#c9d1d9' }));
  initialCells.push(makeCell(fiR, 3, { text: item[2], ta: 'right', bc: '#060708', color: '#9be6a6' }));
  fiR++;
});

// Dense autogenerated market rows (rows 40..117) to make the sheet feel trader-scale
const startDense = 40;
const endDense = 117;
for (let rr = startDense; rr <= endDense; rr++) {
  const tickerNum = rr - startDense + 1;
  const ticker = `TK${String(tickerNum).padStart(3, '0')}`;
  const price = (100 + (tickerNum % 50) + Math.random() * 5).toFixed(2);
  const changeRaw = ((Math.random() - 0.5) * 3).toFixed(2);
  const pct = ((Number(changeRaw) / Number(price)) * 100).toFixed(2) + '%';
  const vol = randInt(50_000, 6_000_000);
  const positive = Number(changeRaw) >= 0;
  const changeColor = positive ? '#23d160' : '#ff6b6b';
  const changeBg = positive ? '#07110a' : '#2a0d0d';
  const rowBg = rr % 2 === 0 ? '#060708' : '#0b1013';

  initialCells.push(makeCell(rr, 1, { text: '2026-02-28', ta: 'center', bc: rowBg, color: '#c9d1d9' }));
  initialCells.push(makeCell(rr, 2, { text: ticker, ta: 'left', bc: rowBg, color: '#ffffff' }));
  initialCells.push(makeCell(rr, 3, { text: price, ta: 'right', bc: rowBg, color: '#9be6a6' }));
  initialCells.push(makeCell(rr, 4, { text: (changeRaw >= 0 ? '+' : '') + changeRaw, ta: 'right', color: changeColor, bc: changeBg }));
  initialCells.push(makeCell(rr, 5, { text: (pct.startsWith('-') ? '' : '+') + pct.replace('+', ''), ta: 'right', color: changeColor, bc: changeBg }));
  initialCells.push(makeCell(rr, 6, { text: formatNumber(vol), ta: 'right', bc: rowBg, color: '#c9d1d9' }));
  initialCells.push(makeCell(rr, 7, { text: ['Large Cap', 'Mid Cap', 'Small Cap'][tickerNum % 3], ta: 'left', bc: rowBg, color: '#c9d1d9' }));
  initialCells.push(makeCell(rr, 8, { text: ['','','Slow day','IPO watch'][tickerNum % 4], ta: 'left', bc: rowBg, color: '#dbe7ff' }));
}

const financeSample = {
  initialCells,
  mergedCells,
  cellHeight: 18,
  cellWidth: 90,
  gridlinesOn: false,
  widthOverrides: { 2: 120, 8: 240 }
};

const out = `const financeSample = ${JSON.stringify(financeSample, null, 2)};\n\nexport default financeSample;\n`;

const dest = path.join(__dirname, '..', 'src', 'sampledata.finance.ts');
fs.writeFileSync(dest, out, 'utf8');
console.log('Wrote', dest);
