import { Rect, GigaSheetTypeOptions } from './interfaces';
import ContextMenu from './components/contextmenu';
import { FormulaBar } from './components/formulaBar';
import { Toolbar } from './components/toolbar';
import { CopyHandler, PasteHandler } from './copypaste';
import { Block } from './components/block';
import HistoryManager from './history';
import KeyboardHandler from './keyboardHandler';
import GridMetrics from './gridmetrics';
import RowNumbers from './rownumbers';
import HeaderIdentifiers from './headeridentifiers';
export default class Sheet {
    wrapper: HTMLElement;
    container: HTMLElement;
    cornerCell: HTMLElement;
    selectionLayer: HTMLElement;
    editInput: HTMLInputElement;
    lastDevicePixelRatio: number;
    lastBlockCanvases: number;
    visibleStartRow: number;
    visibleEndRow: number;
    visibleStartCol: number;
    visibleEndCol: number;
    rowNumberWidth: number;
    headerRowHeight: number;
    cellHeight: number;
    cellWidth: number;
    blockRows: number;
    blockCols: number;
    paddingBlocks: number;
    heightOverrides: any;
    widthOverrides: any;
    gridlinesOn: boolean;
    padding: number;
    activeBlocks: Map<any, any>;
    mergedCells: Rect[];
    elRegistry: any;
    heightAccum: any;
    widthAccum: any;
    data: any;
    parser: any;
    isResizing: boolean;
    activeSelection: any;
    resizeStart: any;
    resizeInitialSize: any;
    busy: boolean;
    rqtimeout: any;
    zoomLevel: number;
    selectedCell: HTMLElement | null;
    isSelecting: boolean;
    selectionStart: {
        row: number;
        col: number;
    } | null;
    selectionEnd: {
        row: number;
        col: number;
    } | null;
    selectionHandle: HTMLElement | null;
    selectedCols: Set<string | number>;
    selectedRows: Set<string | number>;
    draggingHeader: any;
    draggingRow: any;
    editingCell: any;
    selectionBoundRect: any;
    formatButton: HTMLElement;
    _container: HTMLDivElement;
    ctxmenu: ContextMenu;
    formulaBar: FormulaBar | null;
    toolbar: Toolbar | null;
    options: any;
    lastCol: number | null;
    probe: HTMLDivElement;
    scheduledRenders: {
        [key: string]: any;
    };
    scheduledOffBlockRenders: {
        [key: string]: any;
    };
    renderQueued: boolean;
    maxRows: number | null;
    maxCols: number | null;
    initialCells: any;
    widthMaxByCol: any;
    needDims: any;
    dimUpdatesQueued: any;
    measureCanvas: any;
    maxWidthInCol: any;
    historyManager: HistoryManager;
    keyboardHandler: KeyboardHandler;
    copyHandler: CopyHandler;
    pasteHandler: PasteHandler;
    metrics: GridMetrics;
    rowNumbers: RowNumbers;
    headerIdentifiers: HeaderIdentifiers;
    freeze: any;
    _selectionBoundRects: any;
    events: any;
    prevSelectionBoundRect: any;
    constructor(wrapper: HTMLElement, options?: GigaSheetTypeOptions | any);
    intervalSetRandomData(): void;
    initRender(): void;
    buildOverrides(overrides: any): any;
    subscribeFinance(): void;
    subscribeEvent: (eventName: string, cb: any) => void;
    emitEvent: (eventName: string, data?: any) => void;
    hasEvent: (eventName: string) => boolean;
    initEventListeners(): void;
    showContextMenu(x: number, y: number, row: number, col: number): void;
    deleteRow(row?: any, record?: boolean): void;
    deleteCol(col?: any, record?: boolean): void;
    shiftHeightOverrides(pivot: any, amount?: number): void;
    shiftWidthOverrides(pivot: any, amount?: number): void;
    insertRow(row?: any, data?: any, record?: boolean, heightOverride?: any): void;
    insertCol(col?: any, data?: any, record?: boolean, widthOverride?: any): void;
    toggleGridlines(): void;
    scaler(): number;
    clearSelectedCells(): void;
    getColumnName(columnNumber: number): string;
    recordCellBeforeChange(row: number, col: number, attr?: any): void;
    setWidthOverride(col: any, width: any): void;
    setHeightOverride(row: any, height: any): void;
    rerenderCellsForce(arr: any): void;
    rerenderCells(arr: any): void;
    rerenderMerges(arr?: any): void;
    rowColInBounds(row: number, col: number, bounds: any): boolean;
    hideContextMenu(): void;
    handleCellDblClick(e: any): void;
    applyBorder(border: any): void;
    openFormatMenu(): void;
    forceRerender(): void;
    handleKeyDown(e: any): void;
    restoreSave(): boolean;
    getSelectedCells(): any;
    getSelectedCellsOrVirtual(): any;
    getSelectedCellsOrVirtual2D(): any[];
    getSelectedCellsOrVirtualMultiple(): any[];
    getSelectedCellDataSparse(): any;
    isNotMergedOver(row: number, col: number): boolean;
    isMergedOver(row: number, col: number): boolean;
    getTotalRows(): number;
    getTotalCols(): number;
    get shouldDrawGridlines(): boolean;
    get totalRows(): number;
    get totalCols(): number;
    getMerge: (row: number, col: number) => Rect;
    startCellEdit(row: number, col: number, startingValue?: string): void;
    setText(row: number, col: number, text: string): void;
    setCell(row: number, col: number, field: string, value: any): void;
    putCellObj(row: number, col: number, obj: any): void;
    setCellsMutate(cells: any, mutator: Function): void;
    setCells(cells: any, field: string, value: any): void;
    finishCellEdit(): void;
    getBlocksInMerge(merge: any): Set<any>;
    cancelCellEdit(): void;
    updateRenderingQuality(): void;
    createSelectionHandle(): void;
    handleMouseDown(e: any): void;
    getSelectionBoundRects(): any[];
    handleSelectionMouseDown(e: any): void;
    selectCell({ row, col, continuation, clear }: any): void;
    getCellsInRange(startRow: number, startCol: number, endRow: number, endCol: number): any;
    getMergesInRange({ startRow, startCol, endRow, endCol }: Rect): Rect[];
    normalizeCoordinates({ startRow, startCol, endRow, endCol }: {
        startRow: number;
        startCol: number;
        endRow: number;
        endCol: number;
    }): {
        startRow: number;
        startCol: number;
        endRow: number;
        endCol: number;
    };
    getBoundingRectCells(startRow: number, startCol: number, endRow: number, endCol: number): {
        startRow: number;
        startCol: number;
        endRow: number;
        endCol: number;
    };
    handleMouseMove(e: any): void;
    handleMouseUp(e: any): void;
    getCellFromEvent(e: any): {
        row: number;
        col: number;
    };
    mergeSelectedCells(bounds?: any, recordChanges?: boolean): void;
    unmergeSelectedCells(bounds?: any, recordChanges?: boolean): void;
    addNewSelection(): HTMLDivElement;
    getTrueValue(row: number, col: number): any;
    onSelectionChange(): void;
    updateSelection(fromKeyInput?: boolean): void;
    positionSelectionHandle(): void;
    setData(grid?: any, initialData?: any): void;
    createRowNumber(label: string): HTMLDivElement;
    get totalRowBounds(): any;
    get totalColBounds(): any;
    get totalYBounds(): any;
    get totalXBounds(): any;
    updateHeightAccum(): void;
    updateWidthAccum(): void;
    updateGridDimensions(): void;
    atEndWidth(): boolean;
    atEndHeight(): boolean;
    handleScroll(): void;
    updateVisibleGrid(force?: boolean): void;
    blockCanvases(): 1 | 2 | 4;
    createBlock(blockRow: number, blockCol: number): Block;
    effectiveDevicePixelRatio(): number;
    blockKey(block: any): string;
    getKey(row: number, col: number): string;
    getBlock(row: number, col: number): any;
    getSubBlock(row: number, col: number): any;
    setGridlinesCtx(ctx: any, bgc: any): void;
    scale(val: number): number;
    scalex(val: number): number;
    scalec(val: number): number;
    scalef(val: number): number;
    scaleRect(x: number, y: number, width: number, height: number): {
        l: number;
        t: number;
        w: number;
        h: number;
    };
    setBorStroke(ctx: any, borderColor?: string): void;
    setGridLineStroke(ctx: any): void;
    setClearStroke(ctx: any): void;
    strokeLine(ctx: any, x1: number, y1: number, x2: number, y2: number): void;
    getBorder(cell: any, side?: string): any;
    renderBorders(ctx: any, row: number, col: number, fromBlockRender: boolean): void;
    getCtx(row: number, col: number): any;
    getOverlappingRect(rect1: Rect, rect2: Rect): Rect;
    immediateRenderCell(row: any, col: any, fromBlockRender: boolean): void;
    immediateOffBlockRender(row: any, col: any, fromBlockRender: boolean, block: any): void;
    getCellsInMerge(merge: any): any[];
    immediateRenderAll: () => void;
    immediateUpdateDims: () => void;
    updateDim(row: any, col: any): void;
    renderCell(row: any, col: any, fromBlockRender?: boolean): void;
    scalerZoom(): number;
    clearElRegistry(row: number, col: number): void;
    isSelectStart(row: number, col: number): boolean;
    isSelectEnd(row: number, col: number): boolean;
    positionElement(el: any, x: number, y: number, width: number, height: number, append?: boolean): void;
    getCellId(row: number, col: number): any;
    setElRegistry(row: number, col: number, el: any, type: string): void;
    getButton(row: number, col: number): any;
    getLineChart(row: number, col: number): any;
    quality(): "max" | "performance" | "balance";
    applyRenderingQuality(ctx: any): void;
    hasCell(row: number, col: number): boolean;
    getCell(row: number, col: number): any;
    getCellOrMerge(row: number, col: number): any;
    getCellText(row: number, col: number): any;
    getCellTextAlign(row: number, col: number): any;
    renderCellBackground(ctx: any, row: number, col: number): void;
    setTextCtx(ctx: any, row: number, col: number): void;
    renderCellText(ctx: any, row: number, col: number): void;
    getFontSize(row: number, col: number): any;
    getCellColor(row: number, col: number): any;
    getAbbreviatedText(text: string): string;
    getFontString(row?: number | null, col?: number | null): string;
    releaseBlock(block: any): void;
}
